# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
  APPLICATION_SETTINGS: ${{ secrets.APPLICATION_SETTINGS }}
  MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
  MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
  FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
  DATABASE_URI: ${{ secrets.DATABASE_URI }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install git+git://github.com/maxcountryman/flask-uploads.git@master
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest

#  build:
#    needs: test
#
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: BuildImage
#        run: |
#          docker build . --file Dockerfile --tag flaskapp
#          docker images
#
#      - name: PushImage
#        run: |
#          echo "${{ secrets.DOCKER_PWD }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
#          docker images
#          docker tag flaskapp ${{ secrets.DOCKER_LOGIN }}/flaskapp
#          docker images
#          docker push ${{ secrets.DOCKER_LOGIN }}/flaskapp